services:
  web:
      build: .
      ports:
        - "3000:3000"
      environment:
        - DATABASE_URL=${DATABASE_URL}
        - REDIS_URL=redis://redis:6379 # Nome do servi√ßo no Docker
        - RESEND_API_KEY=${RESEND_API_KEY}
      depends_on:
        - redis
      networks:
        - devefficiency
  redis:
    image: redis:alpine
    container_name: redis_otp_cache
    restart: always
    volumes:
      - redis_data:/data
    networks:
        - devefficiency
volumes:
  redis_data:

networks:
  devefficiency:
    external: true
      